/*
 * Code to controll an 8x8x8 ledcube using avr
 * http://www.instructables.com/id/Led-Cube-8x8x8/
 * See lisence.txt for lisence.
 */
#include "main.h"
#include "effect.h"
#include "launch_effect.h"
#include "draw.h"
#include "debug.h"
#include "util.h"

// Main loop
// the AVR enters this function at boot time
int main (void)
{
	// This function initiates IO ports, timers, interrupts and
    // serial communications
	ioinit();

	InitDebug();

	InitUtil();

	//FDEV_SETUP_STREAM(
	m_override_delay = 2;
	
    // This variable specifies which layer is currently being drawn by the
	// cube interrupt routine. We assign a value to it to make sure it's not >7.
	current_layer = 7;
	
	// This variable specifies whether or not self-test is currently being drawn.
	//self_test = 0;

	//Binary mode
	//binary_mode = 0;

	// This gets the value saved in eeprom to be used as seed for
	// the pseudo-random generator.
	uint32_t random_value = eeprom_read_dword(RandomSeed_ptr);

	srand(random_value);

	// Enable interrupts
	// This starts the routine that draws the cube content
	sei();

	// Main loop, does awesome shit forever!
	while (1)
	{
		if(self_test == 0)
		{


			// Show the effects in a random order.

			random_value = rand();
			// This writes the random number to eeprom so that 
			// we can use it as a seed next time the cube restarts
			eeprom_write_dword(RandomSeed_ptr, random_value);
			launch_effect(random_value%EFFECTS_TOTAL);
		}
		else
		{
			OverrideDelay(0);
			self_test = 0;

			SelfTest();
		}
	}
}

const char LayerLookup[] = {2, 1, 0, 3, 4, 5, 6, 7};
const char PlaneYLookup[] = {7, 6, 5, 0, 1, 2, 3, 4};


/*
 * Multiplexer/framebuffer routine
 * This function is called by an interrupt generated by timer 2.
*/
ISR(TIMER2_COMP_vect)
{
	int i;

	// Increment the current_layer counter so that the next layer is
	// drawn the next time this function runs.
	current_layer = (current_layer + 1) % 8;

	LAYER_SELECT = 0x00; // Turn all cathode layers off. (all transistors off)

	// Loop through all 8 bytes of data in the current layer in reverse order
	// and shift it onto the layer.
	for (i = 7; i >= 0; i--)
	{
		// Set the shift clock to 0 
		SHIFTCLK_ADDR &= ~SHIFTCLK_MASK;
		// Set the data on the data-bus of the latch array.
		DATA_BUS = cube[current_layer][PlaneYLookup[i]];
		// Set the shift clock to 1 to create a rising edge and shift in the data on the data bus.
		SHIFTCLK_ADDR |= SHIFTCLK_MASK;
	}

	LAYER_SELECT = _BV(LayerLookup[current_layer]);	// Transistor ON for current layer
}

/*
 * This routine does several things
 * 1: Sends tick to the debug functions.
 * 2: Sends tick to the delay functions.
 * This function is called by an interrupt generated by timer 0.
 * 
*/
ISR(TIMER0_COMP_vect)
{
	DelayTick();

	DebugTick();
}

void ioinit (void)
{
	DDRA = 0x0c;	// EQ AD input and output
	DDRB = 0xff;	// Layer select and ISP
	DDRC = 0xff;	// Data port
	DDRD = 0xf3;	// RS232, buttons, LEDS and shift clock
	
	
	PORTA = 0x00;	// EQ AD input pullup off? EQ outputs off
	PORTB = 0x00;	// Layer select off
	PORTC = 0x00;	// Data port off
	PORTD = 0x04;	// All outputs off, enable pullup on button


	// Timer 0
	// General purpose timer interrupt
	// 14745600/64/230 = 1001 interrupts per second or 1 interrupt every 0,998ms
	OCR0 = 229;
	TCCR0 |= _BV(CS01) | _BV(CS02); // Prescaler = 64.
	TCCR0 |= _BV(WGM01); // CTC mode. Reset counter when OCR0 is reached.
	TCNT0 = 0x00;	// Initial counter value = 0;
	TIMSK |= _BV(OCIE0);	// Enable CTC interrupt.

	// Timer 2
	// Frame buffer interrupt
	// 14745600/128/11 = 10472.72 interrupts per second
	// 10472.72/8 = 1309 frames per second
	OCR2 = 10; 	// interrupt at counter = 10
    TCCR2 |= _BV(CS20) | _BV(CS22); // Prescaler = 128.
	TCCR2 |= _BV(WGM21); // CTC mode. Reset counter when OCR2 is reached.
	TCNT2 = 0x00;	// initial counter value = 0;
	TIMSK |= _BV(OCIE2); // Enable CTC interrupt.
}

void SelfTest()
{
	int i, x, y;

	for(i = 0; i < 7; i++)
	{
		setplane_z(i);
		delay_ms(1000);	
		clrplane_z(i);
	}
	for(x = 0; x <= 7; x++)
	{
		for(y = 0; y <= 7; y++)
		{
			line(x, y, 0, x, y, 7);
			delay_ms(1000);
			fill(0);
		}
	}
}

// Take input from a computer and load it onto the cube buffer
void rs232(void)
{
	int tempval;
	int x = 0;
	int y = 0;
    int escape = 0;
	
	while (1)
	{
		// Switch state on red LED for debugging
		// Should switch state every time the code
		// is waiting for a byte to be received.
		DebugBlink(LED_RED);

		// Wait until a byte has been received
		while ( !(UCSRA & (1<<RXC)) );

		// Load the received byte from rs232 into a buffer.
		tempval = UDR;

		// Uncommet this to echo data back to the computer
		// for debugging purposes.
		//UDR = tempval;

		// Every time the cube receives a 0xff byte,
		// it goes into sync escape mode.
		// if a 0x00 byte is then received, the x and y counters
		// are reset to 0. This way the x and y counters are
		// always the same on the computer and in the cube.
		// To send an 0xff byte, you have to send it twice!

		// Go into sync escape mode
		if (tempval == 0xff)
		{
			// Wait for the next byte
			 while ( !(UCSRA & (1<<RXC)) );
			 // Get the next byte
			 tempval = UDR;

			 // Sync signal is received.
			 // Reset x and y counters to 0.
			 if (tempval == 0x00)
			 {
				x = 0;
				y = 0;
                escape = 1;
			 }
			 // if no 0x00 byte is received, proceed with
			 // the byte we just received.
		}

        if (escape == 0)
        {
			// Load data into the current position in the buffer
			fb[x][y] = tempval;

    		// Check if we have reached the limits of the buffer array.
    		if (y == 7)
    		{
    			if (x == 7)
    			{
    				// All data is loaded. Reset both counters
    				y = 0;
    				x = 0;
                    // Copy the data onto the cube.
    				tmp2cube();
    			} 
				else
    			{
    				// A layer is loaded, reset y and increment x.
    				x++;
    				y = 0;
    			}
    		} 
			else
    		{
    			// We are in the middle of loading a layer. increment y.
    			y++;
    		}
	
	    } 
		else
        {
            escape = 0;
        }
    }
}


